version: '2'

networks:
  hyperledger:

services:
  db:
    container_name: db
    image: postgis/postgis
    ports: 
      - 5432:5432
    networks: 
      - hyperledger
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order-manager
    volumes:
      - ../../state/db:/var/lib/postgresql/data
    restart: always
  pg-admin:
    container_name: pg-admin
    image: dpage/pgadmin4:4.24
    depends_on:
      - db
    ports:
      - 5431:80
    environment: 
      - PGADMIN_DEFAULT_EMAIL=postgres
      - PGADMIN_DEFAULT_PASSWORD=postgres
    networks: 
      - hyperledger
    restart: always
  # nats:
  #   container_name: nats
  #   image: nats:2.1.6
  #   ports:
  #     - 4222:4222
